name: Test

on:

  push:

    branches:

      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  test:
    - name: Install dependencies
      run: |
        npm install
        npm test
